#!/bin/bash

path="$HOME/scripts"
filename=$path/$1

found=1

while read -r app
do 
   all_data=( $app )
   cmd=${all_data[0]}
   name=${all_data[1]}
   url=${all_data[2]}
   if [ $1 = $cmd ]; then
	   echo "FOUND"
       found=0
       break
   fi
done < "$path"/lookup.tbl

if [ $found -eq 1 ]
then
   exit 1
fi

echo "The last time you checked $name was:"

tail -n 6 "$path"/$1.dat

read -p  "Are you sure you want to check it again? (y/n)" go_ahead
go_ahead=${go_ahead:-y}
if [ "y" = $go_ahead ]; then
   date >> "$path"/$1.dat
   firefox $url
else
   exit 0
fi
